# Data Fetcher

In [1]:
import os
import wget
from datetime import datetime, timedelta, date

print('Cek keberadaan direktori ...')
directory = 'fetched'
if os.path.isdir(directory):
    print('Direktori ditemukan !')
else:
    print('Membuat direktori ...')
    os.mkdir(directory)

print('Fetching dimulai ...')
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/'
url += 'csse_covid_19_data/csse_covid_19_daily_reports/'
today = date.today().strftime('%m-%d-%Y')
x = '01-22-2020'
while x < today:
    if os.path.isfile(directory+'/'+x+'.csv'):
        pass
    else:
        wget.download(url+x+'.csv', directory+'/'+x+'.csv')
        print(' -> Sukses unduh '+x+'.csv')
    x = (datetime.strptime(x, '%m-%d-%Y') + timedelta(days=1)).strftime('%m-%d-%Y')
print('Fetching selesai !')

print('Periksa keberadaan file dengan ekstensi .tmp ...')
files_in_directory = os.listdir(directory)
all_tmp = [file for file in files_in_directory if file.endswith(".tmp")]
if len(all_tmp) == 0:
    print('Tidak ada file dengan extensi .tmp !')
else:
    print(f'Ditemukan {len(all_tmp)} buah file dengan extensi .tmp')
    for file in all_tmp:
        path_to_file = os.path.join(directory, file)
        os.remove(path_to_file)
    print('Pembersihan direktori selesai !')
print('Tahap sinkronisasi data selesai !')

Cek keberadaan direktori ...
Membuat direktori ...
Fetching dimulai ...
 -> Sukses unduh 01-22-2020.csv
 -> Sukses unduh 01-23-2020.csv
 -> Sukses unduh 01-24-2020.csv
 -> Sukses unduh 01-25-2020.csv
 -> Sukses unduh 01-26-2020.csv
 -> Sukses unduh 01-27-2020.csv
 -> Sukses unduh 01-28-2020.csv
 -> Sukses unduh 01-29-2020.csv
 -> Sukses unduh 01-30-2020.csv
 -> Sukses unduh 01-31-2020.csv
 -> Sukses unduh 02-01-2020.csv
 -> Sukses unduh 02-02-2020.csv
 -> Sukses unduh 02-03-2020.csv
 -> Sukses unduh 02-04-2020.csv
 -> Sukses unduh 02-05-2020.csv
 -> Sukses unduh 02-06-2020.csv
 -> Sukses unduh 02-07-2020.csv
 -> Sukses unduh 02-08-2020.csv
 -> Sukses unduh 02-09-2020.csv
 -> Sukses unduh 02-10-2020.csv
 -> Sukses unduh 02-11-2020.csv
 -> Sukses unduh 02-12-2020.csv
 -> Sukses unduh 02-13-2020.csv
 -> Sukses unduh 02-14-2020.csv
 -> Sukses unduh 02-15-2020.csv
 -> Sukses unduh 02-16-2020.csv
 -> Sukses unduh 02-17-2020.csv
 -> Sukses unduh 02-18-2020.csv
 -> Sukses unduh 02-19-2020.csv
 -> Sukses unduh 02-20-2020.csv
 -> Sukses unduh 02-21-2020.csv
 -> Sukses unduh 02-22-2020.csv
 -> Sukses unduh 02-23-2020.csv
 -> Sukses unduh 02-24-2020.csv
 -> Sukses unduh 02-25-2020.csv
 -> Sukses unduh 02-26-2020.csv
 -> Sukses unduh 02-27-2020.csv
 -> Sukses unduh 02-28-2020.csv
 -> Sukses unduh 02-29-2020.csv
 -> Sukses unduh 03-01-2020.csv
 -> Sukses unduh 03-02-2020.csv
 -> Sukses unduh 03-03-2020.csv
 -> Sukses unduh 03-04-2020.csv
 -> Sukses unduh 03-05-2020.csv
 -> Sukses unduh 03-06-2020.csv
 -> Sukses unduh 03-07-2020.csv
 -> Sukses unduh 03-08-2020.csv
 -> Sukses unduh 03-09-2020.csv
 -> Sukses unduh 03-10-2020.csv
 -> Sukses unduh 03-11-2020.csv
 -> Sukses unduh 03-12-2020.csv
 -> Sukses unduh 03-13-2020.csv
 -> Sukses unduh 03-14-2020.csv
 -> Sukses unduh 03-15-2020.csv
 -> Sukses unduh 03-16-2020.csv
 -> Sukses unduh 03-17-2020.csv
 -> Sukses unduh 03-18-2020.csv
 -> Sukses unduh 03-19-2020.csv
 -> Sukses unduh 03-20-2020.csv
 -> Sukses unduh 03-21-2020.csv
 -> Sukses unduh 03-22-2020.csv
 -> Sukses unduh 03-23-2020.csv
 -> Sukses unduh 03-24-2020.csv
 -> Sukses unduh 03-25-2020.csv
 -> Sukses unduh 03-26-2020.csv
 -> Sukses unduh 03-27-2020.csv
 -> Sukses unduh 03-28-2020.csv
 -> Sukses unduh 03-29-2020.csv
 -> Sukses unduh 03-30-2020.csv
 -> Sukses unduh 03-31-2020.csv
 -> Sukses unduh 04-01-2020.csv
 -> Sukses unduh 04-02-2020.csv
 -> Sukses unduh 04-03-2020.csv
 -> Sukses unduh 04-04-2020.csv
 -> Sukses unduh 04-05-2020.csv
 -> Sukses unduh 04-06-2020.csv
 -> Sukses unduh 04-07-2020.csv
 -> Sukses unduh 04-08-2020.csv
 -> Sukses unduh 04-09-2020.csv
 -> Sukses unduh 04-10-2020.csv
 -> Sukses unduh 04-11-2020.csv
 -> Sukses unduh 04-12-2020.csv
 -> Sukses unduh 04-13-2020.csv
 -> Sukses unduh 04-14-2020.csv
 -> Sukses unduh 04-15-2020.csv
 -> Sukses unduh 04-16-2020.csv
 -> Sukses unduh 04-17-2020.csv
 -> Sukses unduh 04-18-2020.csv
 -> Sukses unduh 04-19-2020.csv
 -> Sukses unduh 04-20-2020.csv
 -> Sukses unduh 04-21-2020.csv
 -> Sukses unduh 04-22-2020.csv
 -> Sukses unduh 04-23-2020.csv
 -> Sukses unduh 04-24-2020.csv
 -> Sukses unduh 04-25-2020.csv
 -> Sukses unduh 04-26-2020.csv
 -> Sukses unduh 04-27-2020.csv
 -> Sukses unduh 04-28-2020.csv
 -> Sukses unduh 04-29-2020.csv
 -> Sukses unduh 04-30-2020.csv
 -> Sukses unduh 05-01-2020.csv
 -> Sukses unduh 05-02-2020.csv
 -> Sukses unduh 05-03-2020.csv
 -> Sukses unduh 05-04-2020.csv
 -> Sukses unduh 05-05-2020.csv
 -> Sukses unduh 05-06-2020.csv
 -> Sukses unduh 05-07-2020.csv
 -> Sukses unduh 05-08-2020.csv
 -> Sukses unduh 05-09-2020.csv
 -> Sukses unduh 05-10-2020.csv
 -> Sukses unduh 05-11-2020.csv
 -> Sukses unduh 05-12-2020.csv
 -> Sukses unduh 05-13-2020.csv
 -> Sukses unduh 05-14-2020.csv
 -> Sukses unduh 05-15-2020.csv
 -> Sukses unduh 05-16-2020.csv
 -> Sukses unduh 05-17-2020.csv
 -> Sukses unduh 05-18-2020.csv
 -> Sukses unduh 05-19-2020.csv
 -> Sukses unduh 05-20-2020.csv
 -> Sukses unduh 05-21-2020.csv
 -> Sukses unduh 05-22-2020.csv
 -> Sukses unduh 05-23-2020.csv
 -> Sukses unduh 05-24-2020.csv
 -> Sukses unduh 05-25-2020.csv
 -> Sukses unduh 05-26-2020.csv
 -> Sukses unduh 05-27-2020.csv
 -> Sukses unduh 05-28-2020.csv
 -> Sukses unduh 05-29-2020.csv
 -> Sukses unduh 05-30-2020.csv
 -> Sukses unduh 05-31-2020.csv
 -> Sukses unduh 06-01-2020.csv
 -> Sukses unduh 06-02-2020.csv
 -> Sukses unduh 06-03-2020.csv
 -> Sukses unduh 06-04-2020.csv
 -> Sukses unduh 06-05-2020.csv
 -> Sukses unduh 06-06-2020.csv
 -> Sukses unduh 06-07-2020.csv
 -> Sukses unduh 06-08-2020.csv
 -> Sukses unduh 06-09-2020.csv
 -> Sukses unduh 06-10-2020.csv
 -> Sukses unduh 06-11-2020.csv
 -> Sukses unduh 06-12-2020.csv
 -> Sukses unduh 06-13-2020.csv
 -> Sukses unduh 06-14-2020.csv
 -> Sukses unduh 06-15-2020.csv
 -> Sukses unduh 06-16-2020.csv
 -> Sukses unduh 06-17-2020.csv
 -> Sukses unduh 06-18-2020.csv
 -> Sukses unduh 06-19-2020.csv
 -> Sukses unduh 06-20-2020.csv
 -> Sukses unduh 06-21-2020.csv
 -> Sukses unduh 06-22-2020.csv
 -> Sukses unduh 06-23-2020.csv
 -> Sukses unduh 06-24-2020.csv
 -> Sukses unduh 06-25-2020.csv
 -> Sukses unduh 06-26-2020.csv
 -> Sukses unduh 06-27-2020.csv
 -> Sukses unduh 06-28-2020.csv
 -> Sukses unduh 06-29-2020.csv
 -> Sukses unduh 06-30-2020.csv
 -> Sukses unduh 07-01-2020.csv
 -> Sukses unduh 07-02-2020.csv
 -> Sukses unduh 07-03-2020.csv
 -> Sukses unduh 07-04-2020.csv
 -> Sukses unduh 07-05-2020.csv
 -> Sukses unduh 07-06-2020.csv
 -> Sukses unduh 07-07-2020.csv
 -> Sukses unduh 07-08-2020.csv
 -> Sukses unduh 07-09-2020.csv
 -> Sukses unduh 07-10-2020.csv
 -> Sukses unduh 07-11-2020.csv
 -> Sukses unduh 07-12-2020.csv
 -> Sukses unduh 07-13-2020.csv
 -> Sukses unduh 07-14-2020.csv
 -> Sukses unduh 07-15-2020.csv
 -> Sukses unduh 07-16-2020.csv
 -> Sukses unduh 07-17-2020.csv
 -> Sukses unduh 07-18-2020.csv
 -> Sukses unduh 07-19-2020.csv
 -> Sukses unduh 07-20-2020.csv
 -> Sukses unduh 07-21-2020.csv
 -> Sukses unduh 07-22-2020.csv
 -> Sukses unduh 07-23-2020.csv
 -> Sukses unduh 07-24-2020.csv
 -> Sukses unduh 07-25-2020.csv
 -> Sukses unduh 07-26-2020.csv
 -> Sukses unduh 07-27-2020.csv
 -> Sukses unduh 07-28-2020.csv
 -> Sukses unduh 07-29-2020.csv
 -> Sukses unduh 07-30-2020.csv
 -> Sukses unduh 07-31-2020.csv
 -> Sukses unduh 08-01-2020.csv
 -> Sukses unduh 08-02-2020.csv
 -> Sukses unduh 08-03-2020.csv
 -> Sukses unduh 08-04-2020.csv
 -> Sukses unduh 08-05-2020.csv
 -> Sukses unduh 08-06-2020.csv
 -> Sukses unduh 08-07-2020.csv
 -> Sukses unduh 08-08-2020.csv
 -> Sukses unduh 08-09-2020.csv
 -> Sukses unduh 08-10-2020.csv
 -> Sukses unduh 08-11-2020.csv
 -> Sukses unduh 08-12-2020.csv
 -> Sukses unduh 08-13-2020.csv
 -> Sukses unduh 08-14-2020.csv
 -> Sukses unduh 08-15-2020.csv
 -> Sukses unduh 08-16-2020.csv
 -> Sukses unduh 08-17-2020.csv
 -> Sukses unduh 08-18-2020.csv
 -> Sukses unduh 08-19-2020.csv
 -> Sukses unduh 08-20-2020.csv
 -> Sukses unduh 08-21-2020.csv
 -> Sukses unduh 08-22-2020.csv
 -> Sukses unduh 08-23-2020.csv
 -> Sukses unduh 08-24-2020.csv
 -> Sukses unduh 08-25-2020.csv
 -> Sukses unduh 08-26-2020.csv
 -> Sukses unduh 08-27-2020.csv
 -> Sukses unduh 08-28-2020.csv
 -> Sukses unduh 08-29-2020.csv
 -> Sukses unduh 08-30-2020.csv
 -> Sukses unduh 08-31-2020.csv
 -> Sukses unduh 09-01-2020.csv
 -> Sukses unduh 09-02-2020.csv
Fetching selesai !
Periksa keberadaan file dengan ekstensi .tmp ...
Tidak ada file dengan extensi .tmp !
Tahap sinkronisasi data selesai !

# Merging the CSV

In [2]:
import glob
import pandas as pd

all_filenames = [i for i in glob.glob('fetched/*.csv')]
merged_csv = pd.concat([pd.read_csv(f) for f in all_filenames])
merged_csv.to_csv("raw-data.csv", index=False, encoding='utf-8-sig')

# Load merged CSV

In [3]:
df = pd.read_csv('raw-data.csv', low_memory=False)
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,Latitude,Longitude
0,Hubei,Mainland China,1/28/20 23:00,3554.0,125.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Guangdong,Mainland China,1/28/20 23:00,207.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zhejiang,Mainland China,1/28/20 23:00,173.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Henan,Mainland China,1/28/20 23:00,168.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hunan,Mainland China,1/28/20 23:00,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594783,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,Unknown,Colombia,2020-07-17 22:34:48,NaN,NaN,0.0,"Unknown, Colombia",NaN,NaN,NaN,NaN
594784,NaN,NaN,NaN,1.0,0.0,0.0,2070.0,Dillingham,Alaska,US,2020-07-17 18:35:12,59.796037,-158.238194,1.0,"Dillingham, Alaska, US",20.341741,0.0,NaN,NaN
594785,NaN,NaN,NaN,13.0,0.0,13.0,NaN,NaN,Grand Princess,Canada,2020-07-13 12:34:33,NaN,NaN,0.0,"Grand Princess, Canada",NaN,0.0,NaN,NaN
594786,NaN,NaN,NaN,1.0,0.0,0.0,16061.0,Lewis,Idaho,US,2020-07-10 02:34:22,46.233153,-116.434146,1.0,"Lewis, Idaho, US",26.055237,0.0,NaN,NaN
594787,NaN,NaN,NaN,0.0,0.0,0.0,41069.0,Wheeler,Oregon,US,2020-07-06 19:33:59,44.726982,-120.028143,0.0,"Wheeler, Oregon, US",0.000000,NaN,NaN,NaN

In [ ]:
Data di atas masih dalam keadaan kotor. Ada beberapa kolom yang tercantum dalam keadaan terduplikat (namun memiliki nama yang mirip)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590834 entries, 0 to 590833
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Province/State       4358 non-null    object
 1   Country/Region       7617 non-null    object
 2   Last Update          7617 non-null    object
 3   Confirmed            590815 non-null  float64
 4   Deaths               590393 non-null  float64
 5   Recovered            590446 non-null  float64
 6   FIPS                 497759 non-null  float64
 7   Admin2               498767 non-null  object
 8   Province_State       554819 non-null  object
 9   Country_Region       583217 non-null  object
 10  Last_Update          583217 non-null  object
 11  Lat                  572279 non-null  float64
 12  Long_                572279 non-null  float64
 13  Active               583034 non-null  float64
 14  Combined_Key         583217 non-null  object
 15  Incidence_Rate       361085 non-null  float64
 16  Case-Fatality_Ratio  363313 non-null  float64
 17  Latitude             4799 non-null    float64
 18  Longitude            4799 non-null    float64
dtypes: float64(11), object(8)
memory usage: 85.6+ MB

In [84]:
null_index_in_countryRegion = df[df['Country/Region'].isnull()].index
# Index untuk setiap feature 'Country/Region' yang null

get_loc_countryRegion = df.columns.get_loc('Country/Region')
# Mencari kolom pada urutan ke berapa yang memiliki nama 'Country/Region'

for i in null_index_in_countryRegion:
    df.iat[i, get_loc_countryRegion] = df['Country_Region'][i]

In [76]:
df[df['Country/Region'].isnull()]

Empty DataFrame
Columns: [Province/State, Country/Region, Last Update, Confirmed, Deaths, Recovered, FIPS, Admin2, Province_State, Country_Region, Last_Update, Lat, Long_, Active, Combined_Key, Incidence_Rate, Case-Fatality_Ratio, Latitude, Longitude]
Index: []

In [77]:
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,Latitude,Longitude
0,Hubei,Mainland China,1/28/20 23:00,3554.0,125.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Guangdong,Mainland China,1/28/20 23:00,207.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zhejiang,Mainland China,1/28/20 23:00,173.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Henan,Mainland China,1/28/20 23:00,168.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hunan,Mainland China,1/28/20 23:00,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590829,NaN,Colombia,NaN,0.0,0.0,0.0,NaN,NaN,Unknown,Colombia,2020-07-17 22:34:48,NaN,NaN,0.0,"Unknown, Colombia",NaN,NaN,NaN,NaN
590830,NaN,US,NaN,1.0,0.0,0.0,2070.0,Dillingham,Alaska,US,2020-07-17 18:35:12,59.796037,-158.238194,1.0,"Dillingham, Alaska, US",20.341741,0.0,NaN,NaN
590831,NaN,Canada,NaN,13.0,0.0,13.0,NaN,NaN,Grand Princess,Canada,2020-07-13 12:34:33,NaN,NaN,0.0,"Grand Princess, Canada",NaN,0.0,NaN,NaN
590832,NaN,US,NaN,1.0,0.0,0.0,16061.0,Lewis,Idaho,US,2020-07-10 02:34:22,46.233153,-116.434146,1.0,"Lewis, Idaho, US",26.055237,0.0,NaN,NaN
590833,NaN,US,NaN,0.0,0.0,0.0,41069.0,Wheeler,Oregon,US,2020-07-06 19:33:59,44.726982,-120.028143,0.0,"Wheeler, Oregon, US",0.000000,NaN,NaN,NaN

In [85]:
df.drop('Country_Region', axis=1, inplace=True)

In [86]:
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,Latitude,Longitude
0,Hubei,Mainland China,1/28/20 23:00,3554.0,125.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Guangdong,Mainland China,1/28/20 23:00,207.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zhejiang,Mainland China,1/28/20 23:00,173.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Henan,Mainland China,1/28/20 23:00,168.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Hunan,Mainland China,1/28/20 23:00,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590829,NaN,Colombia,NaN,0.0,0.0,0.0,NaN,NaN,Unknown,2020-07-17 22:34:48,NaN,NaN,0.0,"Unknown, Colombia",NaN,NaN,NaN,NaN
590830,NaN,US,NaN,1.0,0.0,0.0,2070.0,Dillingham,Alaska,2020-07-17 18:35:12,59.796037,-158.238194,1.0,"Dillingham, Alaska, US",20.341741,0.0,NaN,NaN
590831,NaN,Canada,NaN,13.0,0.0,13.0,NaN,NaN,Grand Princess,2020-07-13 12:34:33,NaN,NaN,0.0,"Grand Princess, Canada",NaN,0.0,NaN,NaN
590832,NaN,US,NaN,1.0,0.0,0.0,16061.0,Lewis,Idaho,2020-07-10 02:34:22,46.233153,-116.434146,1.0,"Lewis, Idaho, US",26.055237,0.0,NaN,NaN
590833,NaN,US,NaN,0.0,0.0,0.0,41069.0,Wheeler,Oregon,2020-07-06 19:33:59,44.726982,-120.028143,0.0,"Wheeler, Oregon, US",0.000000,NaN,NaN,NaN

In [12]:
import pandas as pd
df = pd.read_csv('test.csv', encoding= 'unicode_escape', low_memory=False)
df

,Model,Make,Model.1,Vehicle Class,Engine Size,Cylinders,Transmission,Fuel,Fuel Consumption,Unnamed: 9,...,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220
0,Year,NaN,NaN,NaN,(L),NaN,NaN,Type,City (L/100 km),Hwy (L/100 km),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,Acura,ILX,Compact,2.4,4.0,AM8,Z,9.9,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020,Acura,MDX SH-AWD,SUV: Small,3.5,6.0,AS9,Z,12.3,9.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020,Acura,MDX SH-AWD A-SPEC,SUV: Small,3.5,6.0,AS9,Z,12.2,9.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020,Acura,MDX Hybrid AWD,SUV: Small,3.0,6.0,AM7,Z,9.1,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.describe()

,Cylinders,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,...,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220
count,891.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,5.672278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.934403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN